/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v13.1
processor: MC56F83783
package_id: MC56F83783VLH
mcu_data: ksdk2_0
processor_version: 13.0.2
external_user_signals: {}
pin_labels:
- {pin_num: '41', pin_signal: GPIOF4/TXD1/XB_OUT8/PWMA_0X/PWMA_FAULT6, label: PWM_SR_L, identifier: PWM_SR_L}
- {pin_num: '42', pin_signal: GPIOF5/RXD1/XB_OUT9/PWMA_1X/PWMA_FAULT7, label: PWM_SR_H, identifier: PWM_SR_H}
- {pin_num: '59', pin_signal: GPIOF7/TB3/CMPC_O/XB_IN3, label: SW_N, identifier: relay;SW_N}
- {pin_num: '40', pin_signal: GPIOF3/SDA1/XB_OUT7, label: SW_GRID, identifier: PWM_H;SW_GRID}
- {pin_num: '39', pin_signal: GPIOF2/SCL1/XB_OUT6, label: user_LED2, identifier: PWM_L;TP1;LED2;user_LED2}
- {pin_num: '12', pin_signal: GPIOA4/ANA4/CMPD_IN0, label: current_bus}
- {pin_num: '13', pin_signal: GPIOA0/ANA0/CMPA_IN3/CMPC_O, label: current_P_inv}
- {pin_num: '32', pin_signal: GPIOC7/SS0_B/TXD0/XB_IN8/XB_OUT6, label: user_LED2, identifier: CC_TP2;LED2}
- {pin_num: '34', pin_signal: GPIOC9/SCLK0/XB_IN4/TXD0/XB_OUT8, label: CC_TP4, identifier: CC_TP4}
- {pin_num: '19', pin_signal: GPIOB6/ANB6/CMPB_IN1, label: test_ac, identifier: test_ac}
- {pin_num: '10', pin_signal: GPIOA6/ANA6, label: test_dc, identifier: test_dc}
- {pin_num: '27', pin_signal: GPIOB2/ANB2/VREFHB/CMPC_IN3, label: current_grid}
- {pin_num: '25', pin_signal: GPIOB1/ANB1/CMPB_IN0/DACB_O, label: current_N_inv}
- {pin_num: '20', pin_signal: GPIOB5/ANB5/CMPC_IN2, label: bus voltage}
- {pin_num: '14', pin_signal: GPIOA1/ANA1/CMPA_IN0, label: voltage_load}
- {pin_num: '24', pin_signal: GPIOB0/ANB0/CMPB_IN3, label: temperature}
- {pin_num: '15', pin_signal: GPIOA2/ANA2/VREFHA/CMPA_IN1, label: voltage_grid}
- {pin_num: '16', pin_signal: GPIOA3/ANA3/VREFLA/CMPA_IN2, label: current_capacitor}
- {pin_num: '28', pin_signal: GPIOB3/ANB3/VREFLB/CMPC_IN0, label: voltage bias}
- {pin_num: '21', pin_signal: GPIOB4/ANB4/CMPC_IN1, label: voltage_inverter}
- {pin_num: '58', pin_signal: GPIOF6/TB2/PWMA_3X/PWMB_3X/XB_IN2, label: SW_L, identifier: SW_L}
- {pin_num: '3', pin_signal: GPIOC0/EXTAL/CLKIN0, label: user_LED1, identifier: LED1;user_LED1}
- {pin_num: '4', pin_signal: GPIOC1/XTAL, label: LED_HVP, identifier: LED;LED_HVP}
- {pin_num: '8', pin_signal: GPIOC4/TA1/CMPB_O/XB_IN8/EWM_OUT_B, label: phase_capture, identifier: Tc;T;C;phase_capture}
- {pin_num: '18', pin_signal: GPIOC5/DACA_O/XB_IN7, label: phase_transfer, identifier: C;T;phase_transfer}
- {pin_num: '53', pin_signal: GPIOE6/PWMA_3B/XB_IN4/PWMB_2B/XB_OUT10, label: PWM_TP}
- {pin_num: '36', pin_signal: GPIOF0/XB_IN6/TB2, label: TP40, identifier: TP2;XBAR_TP2;TP40}
- {pin_num: '49', pin_signal: GPIOC13/TA3/XB_IN6/EWM_OUT_B, label: TP38, identifier: TP1;XBAR_TP1;TP38}
- {pin_num: '56', pin_signal: GPIOC15/SCL0/XB_OUT5/PWMA_FAULT5, label: CAN_STB, identifier: STB;STB_CAN;CAN_STB}
- {pin_num: '46', pin_signal: GPIOE1/PWMA_0A/XB_OUT5, label: PWM1, identifier: PWM1}
- {pin_num: '45', pin_signal: GPIOE0/PWMA_0B/XB_OUT4, label: PWM2, identifier: PWM2}
- {pin_num: '48', pin_signal: GPIOE3/PWMA_1A/XB_OUT7, label: PWM3, identifier: PWM3}
- {pin_num: '47', pin_signal: GPIOE2/PWMA_1B/XB_OUT6, label: PWM4, identifier: PWM4}
- {pin_num: '52', pin_signal: GPIOE5/PWMA_2A/XB_IN3/XB_OUT9, label: PWM5, identifier: PWM5}
- {pin_num: '51', pin_signal: GPIOE4/PWMA_2B/XB_IN2/XB_OUT8, label: PWM6, identifier: PWM6}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_sim.h"
#include "fsl_gpio.h"
#include "fsl_xbara.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '37', peripheral: QSCI1, signal: TXD, pin_signal: GPIOC11/CANTX/SCL1/TXD1}
  - {pin_num: '38', peripheral: QSCI1, signal: RXD, pin_signal: GPIOC12/CANRX/SDA1/RXD1}
  - {pin_num: '46', peripheral: PWMA, signal: 'A, 0', pin_signal: GPIOE1/PWMA_0A/XB_OUT5, identifier: ''}
  - {pin_num: '45', peripheral: PWMA, signal: 'B, 0', pin_signal: GPIOE0/PWMA_0B/XB_OUT4, identifier: ''}
  - {pin_num: '48', peripheral: GPIOE, signal: 'GPIO, 3', pin_signal: GPIOE3/PWMA_1A/XB_OUT7, direction: OUTPUT}
  - {pin_num: '47', peripheral: GPIOE, signal: 'GPIO, 2', pin_signal: GPIOE2/PWMA_1B/XB_OUT6, direction: OUTPUT}
  - {peripheral: PWMA, signal: 'FAULT, 0', pin_signal: CMPA_OUT}
  - {peripheral: PWMA, signal: 'FAULT, 1', pin_signal: CMPB_OUT}
  - {peripheral: PWMA, signal: 'FAULT, 2', pin_signal: CMPC_OUT}
  - {peripheral: ADC, signal: 'SYNC, A', pin_signal: PWMA0_OUT_TRIG0}
  - {pin_num: '13', peripheral: ADC, signal: 'ANA, 0', pin_signal: GPIOA0/ANA0/CMPA_IN3/CMPC_O}
  - {pin_num: '14', peripheral: ADC, signal: 'ANA, 1', pin_signal: GPIOA1/ANA1/CMPA_IN0}
  - {pin_num: '15', peripheral: ADC, signal: 'ANA, 2', pin_signal: GPIOA2/ANA2/VREFHA/CMPA_IN1}
  - {pin_num: '16', peripheral: ADC, signal: 'ANA, 3', pin_signal: GPIOA3/ANA3/VREFLA/CMPA_IN2}
  - {pin_num: '12', peripheral: ADC, signal: 'ANA, 4', pin_signal: GPIOA4/ANA4/CMPD_IN0}
  - {pin_num: '24', peripheral: ADC, signal: 'ANB, 0', pin_signal: GPIOB0/ANB0/CMPB_IN3}
  - {pin_num: '25', peripheral: ADC, signal: 'ANB, 1', pin_signal: GPIOB1/ANB1/CMPB_IN0/DACB_O}
  - {pin_num: '27', peripheral: ADC, signal: 'ANB, 2', pin_signal: GPIOB2/ANB2/VREFHB/CMPC_IN3}
  - {pin_num: '28', peripheral: ADC, signal: 'ANB, 3', pin_signal: GPIOB3/ANB3/VREFLB/CMPC_IN0}
  - {pin_num: '21', peripheral: ADC, signal: 'ANB, 4', pin_signal: GPIOB4/ANB4/CMPC_IN1}
  - {pin_num: '20', peripheral: ADC, signal: 'ANB, 5', pin_signal: GPIOB5/ANB5/CMPC_IN2}
  - {pin_num: '13', peripheral: CMPA, signal: 'IN, 3', pin_signal: GPIOA0/ANA0/CMPA_IN3/CMPC_O}
  - {pin_num: '25', peripheral: CMPB, signal: 'IN, 0', pin_signal: GPIOB1/ANB1/CMPB_IN0/DACB_O}
  - {pin_num: '20', peripheral: CMPC, signal: 'IN, 2', pin_signal: GPIOB5/ANB5/CMPC_IN2}
  - {pin_num: '8', peripheral: GPIOC, signal: 'GPIO, 4', pin_signal: GPIOC4/TA1/CMPB_O/XB_IN8/EWM_OUT_B, identifier: phase_capture, direction: INPUT}
  - {pin_num: '18', peripheral: GPIOC, signal: 'GPIO, 5', pin_signal: GPIOC5/DACA_O/XB_IN7, identifier: phase_transfer, direction: OUTPUT}
  - {pin_num: '40', peripheral: GPIOF, signal: 'GPIO, 3', pin_signal: GPIOF3/SDA1/XB_OUT7, identifier: SW_GRID, direction: OUTPUT}
  - {pin_num: '58', peripheral: GPIOF, signal: 'GPIO, 6', pin_signal: GPIOF6/TB2/PWMA_3X/PWMB_3X/XB_IN2, direction: OUTPUT}
  - {pin_num: '59', peripheral: GPIOF, signal: 'GPIO, 7', pin_signal: GPIOF7/TB3/CMPC_O/XB_IN3, identifier: SW_N, direction: OUTPUT}
  - {pin_num: '56', peripheral: GPIOC, signal: 'GPIO, 15', pin_signal: GPIOC15/SCL0/XB_OUT5/PWMA_FAULT5, identifier: CAN_STB, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '3', peripheral: GPIOC, signal: 'GPIO, 0', pin_signal: GPIOC0/EXTAL/CLKIN0, identifier: user_LED1, direction: OUTPUT}
  - {pin_num: '4', peripheral: GPIOC, signal: 'GPIO, 1', pin_signal: GPIOC1/XTAL, identifier: LED_HVP, direction: OUTPUT}
  - {pin_num: '39', peripheral: GPIOF, signal: 'GPIO, 2', pin_signal: GPIOF2/SCL1/XB_OUT6, identifier: user_LED2, direction: OUTPUT}
  - {pin_num: '49', peripheral: GPIOC, signal: 'GPIO, 13', pin_signal: GPIOC13/TA3/XB_IN6/EWM_OUT_B, identifier: TP38, direction: OUTPUT}
  - {pin_num: '36', peripheral: GPIOF, signal: 'GPIO, 0', pin_signal: GPIOF0/XB_IN6/TB2, identifier: TP40, direction: OUTPUT}
  - {pin_num: '7', peripheral: QSCI0, signal: RXD, pin_signal: GPIOC3/TA0/CMPA_O/RXD0/CLKIN1}
  - {pin_num: '5', peripheral: QSCI0, signal: TXD, pin_signal: GPIOC2/TXD0/TB0/XB_IN2/CLKO0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* GPIOA IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOA);
    /* GPIOB IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOB);
    /* GPIOC IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOC);
    /* GPIOE IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOE);
    /* GPIOF IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOF);
    /* Enable peripheral functionality on pin GPIOA0 (pin 13) */
    GPIO_PinSetPeripheralMode(GPIOA, kGPIO_Pin0, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOA0 (pin 13) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_A0_ANA0_and_CMPA_IN3);
    /* Enable peripheral functionality on pin GPIOA1 (pin 14) */
    GPIO_PinSetPeripheralMode(GPIOA, kGPIO_Pin1, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOA2 (pin 15) */
    GPIO_PinSetPeripheralMode(GPIOA, kGPIO_Pin2, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOA3 (pin 16) */
    GPIO_PinSetPeripheralMode(GPIOA, kGPIO_Pin3, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOA4 (pin 12) */
    GPIO_PinSetPeripheralMode(GPIOA, kGPIO_Pin4, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB0 (pin 24) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin0, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB1 (pin 25) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin1, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOB1 (pin 25) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_B1_ANB1_and_CMPB_IN0);
    /* Enable peripheral functionality on pin GPIOB2 (pin 27) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin2, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB3 (pin 28) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin3, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB4 (pin 21) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin4, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB5 (pin 20) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin5, kGPIO_ModePeripheral);
    /* GPIO functionality on pin GPIOC0 (pin 3) */
    GPIO_PinSetPeripheralMode(BOARD_user_LED1_GPIO, BOARD_user_LED1_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC1 (pin 4) */
    GPIO_PinSetPeripheralMode(BOARD_LED_HVP_GPIO, BOARD_LED_HVP_PIN_MASK, kGPIO_ModeGpio);
    /* Enable peripheral functionality on pin GPIOC2 (pin 5) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin2, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC2 (pin 5) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C2_TXD0);
    /* Enable peripheral functionality on pin GPIOC3 (pin 7) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin3, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC3 (pin 7) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C3_RXD0);
    /* GPIO functionality on pin GPIOC4 (pin 8) */
    GPIO_PinSetPeripheralMode(BOARD_phase_capture_GPIO, BOARD_phase_capture_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC5 (pin 18) */
    GPIO_PinSetPeripheralMode(BOARD_phase_transfer_GPIO, BOARD_phase_transfer_PIN_MASK, kGPIO_ModeGpio);
    /* Enable peripheral functionality on pin GPIOC11 (pin 37) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin11, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC11 (pin 37) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C11_TXD1);
    /* Enable peripheral functionality on pin GPIOC12 (pin 38) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin12, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC12 (pin 38) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C12_RXD1);
    /* GPIO functionality on pin GPIOC13 (pin 49) */
    GPIO_PinSetPeripheralMode(BOARD_TP38_GPIO, BOARD_TP38_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC15 (pin 56) */
    GPIO_PinSetPeripheralMode(BOARD_CAN_STB_GPIO, BOARD_CAN_STB_PIN_MASK, kGPIO_ModeGpio);
    /* Enable peripheral functionality on pin GPIOE0 (pin 45) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin0, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE0 (pin 45) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E0_PWMA_0B);
    /* Enable peripheral functionality on pin GPIOE1 (pin 46) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin1, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE1 (pin 46) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E1_PWMA_0A);
    /* GPIO functionality on pin GPIOE2 (pin 47) */
    GPIO_PinSetPeripheralMode(BOARD_PWM4_GPIO, BOARD_PWM4_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOE3 (pin 48) */
    GPIO_PinSetPeripheralMode(BOARD_PWM3_GPIO, BOARD_PWM3_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOF0 (pin 36) */
    GPIO_PinSetPeripheralMode(BOARD_TP40_GPIO, BOARD_TP40_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOF2 (pin 39) */
    GPIO_PinSetPeripheralMode(BOARD_user_LED2_GPIO, BOARD_user_LED2_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOF3 (pin 40) */
    GPIO_PinSetPeripheralMode(BOARD_SW_GRID_GPIO, BOARD_SW_GRID_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOF6 (pin 58) */
    GPIO_PinSetPeripheralMode(BOARD_SW_L_GPIO, BOARD_SW_L_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOF7 (pin 59) */
    GPIO_PinSetPeripheralMode(BOARD_SW_N_GPIO, BOARD_SW_N_PIN_MASK, kGPIO_ModeGpio);

    /* Initialize GPIO functionality on pin GPIOC4 (pin 8)  */
    GPIO_PinSetDirection(BOARD_phase_capture_GPIO, BOARD_phase_capture_PIN_MASK, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOC0 (pin 3)  */
    GPIO_PinWrite(BOARD_user_LED1_GPIO, BOARD_user_LED1_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_user_LED1_GPIO, BOARD_user_LED1_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOC1 (pin 4)  */
    GPIO_PinWrite(BOARD_LED_HVP_GPIO, BOARD_LED_HVP_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_LED_HVP_GPIO, BOARD_LED_HVP_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOC5 (pin 18)  */
    GPIO_PinWrite(BOARD_phase_transfer_GPIO, BOARD_phase_transfer_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_phase_transfer_GPIO, BOARD_phase_transfer_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOC13 (pin 49)  */
    GPIO_PinWrite(BOARD_TP38_GPIO, BOARD_TP38_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_TP38_GPIO, BOARD_TP38_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOC15 (pin 56)  */
    GPIO_PinWrite(BOARD_CAN_STB_GPIO, BOARD_CAN_STB_PIN_MASK, kGPIO_OutputHigh);
    GPIO_PinSetDirection(BOARD_CAN_STB_GPIO, BOARD_CAN_STB_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOE2 (pin 47)  */
    GPIO_PinWrite(BOARD_PWM4_GPIO, BOARD_PWM4_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_PWM4_GPIO, BOARD_PWM4_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOE3 (pin 48)  */
    GPIO_PinWrite(BOARD_PWM3_GPIO, BOARD_PWM3_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_PWM3_GPIO, BOARD_PWM3_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOF0 (pin 36)  */
    GPIO_PinWrite(BOARD_TP40_GPIO, BOARD_TP40_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_TP40_GPIO, BOARD_TP40_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOF2 (pin 39)  */
    GPIO_PinWrite(BOARD_user_LED2_GPIO, BOARD_user_LED2_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_user_LED2_GPIO, BOARD_user_LED2_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOF3 (pin 40)  */
    GPIO_PinWrite(BOARD_SW_GRID_GPIO, BOARD_SW_GRID_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_SW_GRID_GPIO, BOARD_SW_GRID_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOF6 (pin 58)  */
    GPIO_PinWrite(BOARD_SW_L_GPIO, BOARD_SW_L_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_SW_L_GPIO, BOARD_SW_L_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOF7 (pin 59)  */
    GPIO_PinWrite(BOARD_SW_N_GPIO, BOARD_SW_N_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_SW_N_GPIO, BOARD_SW_N_PIN_MASK, kGPIO_DigitalOutput);

    /* Internal Peripheral Select */
    /* Select PWMA Fault 0 Input.: Select PWMA Fault 0 Input, XB_OUT29. */
    SIM_SetInternalPeriInput(SIM, kSIM_PWMAFault0InputIndex, kSIM_PWMAFault0Input_XB_OUT29);
    /* Select PWMA Fault 1 Input.: Select PWMA Fault 1 Input, XB_OUT30. */
    SIM_SetInternalPeriInput(SIM, kSIM_PWMAFault1InputIndex, kSIM_PWMAFault1Input_XB_OUT30);
    /* Select PWMA Fault 2 Input.: Select PWMA Fault 2 Input, XB_OUT31. */
    SIM_SetInternalPeriInput(SIM, kSIM_PWMAFault2InputIndex, kSIM_PWMAFault2Input_XB_OUT31);

    /* PWM Select */
    /* xbar input 28.: xbar input 28, PWMA0_OUT_TRIG0. */
    SIM_SetXbarInputPWMSelection(SIM, kSIM_XBARIN28Index, kSIM_XbarIn28PWMA0OutTrig0);

    /* CMPA_OUT output assigned to XBARA_IN12 input is connected
     * to XBARA_OUT29 output assigned to PWMA_PWMB_FAULT0 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputCmpaOut, kXBARA_OutputPwmaPwmbFault0);
    /* CMPB_OUT output assigned to XBARA_IN13 input is connected
     * to XBARA_OUT30 output assigned to PWMA_PWMB_FAULT1 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputCmpbOut, kXBARA_OutputPwmaPwmbFault1);
    /* CMPC_OUT output assigned to XBARA_IN14 input is connected
     * to XBARA_OUT31 output assigned to PWMA_PWMB_FAULT2 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputCmpcOut, kXBARA_OutputPwmaPwmbFault2);
    /* PWMB0_MUX_PWMA0_OUT_TRIG0 output assigned to XBARA_IN28 input is connected
     * to XBARA_OUT12 output assigned to ADCA_SYNC */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputPwmb0MuxPwma0OutTrig0, kXBARA_OutputAdcaSync);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
