/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name GPIOE3 (number 48), PWM3
  @{ */
#define BOARD_PWM3_GPIO GPIOE          /*!<@brief GPIO device name: GPIOE */
#define BOARD_PWM3_PIN 3U              /*!<@brief GPIOE pin index: 3 */
#define BOARD_PWM3_PIN_MASK kGPIO_Pin3 /*!<@brief PORT pin mask */
                                       /* @} */

/*! @name GPIOE2 (number 47), PWM4
  @{ */
#define BOARD_PWM4_GPIO GPIOE          /*!<@brief GPIO device name: GPIOE */
#define BOARD_PWM4_PIN 2U              /*!<@brief GPIOE pin index: 2 */
#define BOARD_PWM4_PIN_MASK kGPIO_Pin2 /*!<@brief PORT pin mask */
                                       /* @} */

/*! @name GPIOC4 (number 8), phase_capture
  @{ */
#define BOARD_phase_capture_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BOARD_phase_capture_PIN 4U              /*!<@brief GPIOC pin index: 4 */
#define BOARD_phase_capture_PIN_MASK kGPIO_Pin4 /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name GPIOC5 (number 18), phase_transfer
  @{ */
#define BOARD_phase_transfer_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BOARD_phase_transfer_PIN 5U              /*!<@brief GPIOC pin index: 5 */
#define BOARD_phase_transfer_PIN_MASK kGPIO_Pin5 /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name GPIOF3 (number 40), SW_GRID
  @{ */
#define BOARD_SW_GRID_GPIO GPIOF          /*!<@brief GPIO device name: GPIOF */
#define BOARD_SW_GRID_PIN 3U              /*!<@brief GPIOF pin index: 3 */
#define BOARD_SW_GRID_PIN_MASK kGPIO_Pin3 /*!<@brief PORT pin mask */
                                          /* @} */

/*! @name GPIOF6 (number 58), SW_L
  @{ */
#define BOARD_SW_L_GPIO GPIOF          /*!<@brief GPIO device name: GPIOF */
#define BOARD_SW_L_PIN 6U              /*!<@brief GPIOF pin index: 6 */
#define BOARD_SW_L_PIN_MASK kGPIO_Pin6 /*!<@brief PORT pin mask */
                                       /* @} */

/*! @name GPIOF7 (number 59), SW_N
  @{ */
#define BOARD_SW_N_GPIO GPIOF          /*!<@brief GPIO device name: GPIOF */
#define BOARD_SW_N_PIN 7U              /*!<@brief GPIOF pin index: 7 */
#define BOARD_SW_N_PIN_MASK kGPIO_Pin7 /*!<@brief PORT pin mask */
                                       /* @} */

/*! @name GPIOC15 (number 56), CAN_STB
  @{ */
#define BOARD_CAN_STB_GPIO GPIOC           /*!<@brief GPIO device name: GPIOC */
#define BOARD_CAN_STB_PIN 15U              /*!<@brief GPIOC pin index: 15 */
#define BOARD_CAN_STB_PIN_MASK kGPIO_Pin15 /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name GPIOC0 (number 3), user_LED1
  @{ */
#define BOARD_user_LED1_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BOARD_user_LED1_PIN 0U              /*!<@brief GPIOC pin index: 0 */
#define BOARD_user_LED1_PIN_MASK kGPIO_Pin0 /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name GPIOC1 (number 4), LED_HVP
  @{ */
#define BOARD_LED_HVP_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BOARD_LED_HVP_PIN 1U              /*!<@brief GPIOC pin index: 1 */
#define BOARD_LED_HVP_PIN_MASK kGPIO_Pin1 /*!<@brief PORT pin mask */
                                          /* @} */

/*! @name GPIOF2 (number 39), user_LED2
  @{ */
#define BOARD_user_LED2_GPIO GPIOF          /*!<@brief GPIO device name: GPIOF */
#define BOARD_user_LED2_PIN 2U              /*!<@brief GPIOF pin index: 2 */
#define BOARD_user_LED2_PIN_MASK kGPIO_Pin2 /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name GPIOC13 (number 49), TP38
  @{ */
#define BOARD_TP38_GPIO GPIOC           /*!<@brief GPIO device name: GPIOC */
#define BOARD_TP38_PIN 13U              /*!<@brief GPIOC pin index: 13 */
#define BOARD_TP38_PIN_MASK kGPIO_Pin13 /*!<@brief PORT pin mask */
                                        /* @} */

/*! @name GPIOF0 (number 36), TP40
  @{ */
#define BOARD_TP40_GPIO GPIOF          /*!<@brief GPIO device name: GPIOF */
#define BOARD_TP40_PIN 0U              /*!<@brief GPIOF pin index: 0 */
#define BOARD_TP40_PIN_MASK kGPIO_Pin0 /*!<@brief PORT pin mask */
                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
